name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.0.3"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build and test with Rake
        run: bundle exec rake
